# ansible-playbook -v -i ~/ansible/hosts /playbooks/setup-retropie-mini-snes.yml
---
- hosts: nesclassics
  gather_facts: yes
  vars:

    smb_rom_share: //VHSTORE/ROMS
    smb_rom_folder: Systems
    smb_es_folder: emulationstation
    boot_config_options:
      # Enable audio (loads snd_bcm2835)
      - regexp: "^#?dtparam"
        line: "dtparam=audio=on"

      # Set the GPU memory split value.
      - regexp: "^#?gpu_mem_1024"
        line: "gpu_mem_1024=256"

      # RetroPie Reccomended Settings for Pi 3
      - regexp: "^#?arm_freq"
        line: "arm_freq=1300"      
      - regexp: "^#?gpu_freq"
        line: "gpu_freq=500"      
      - regexp: "^#?core_freq"
        line: "core_freq=500"      
      - regexp: "^#?sdram_freq"
        line: "sdram_freq=500"      
      - regexp: "^#?sdram_schmoo"
        line: "sdram_schmoo=0x02000020"      
      - regexp: "^#?over_voltage"
        line: "over_voltage=2"      
      - regexp: "^#?sdram_over_voltage"
        line: "sdram_over_voltage=2"

      # HDMI & Screen
      - regexp: "^#?hdmi_force_hotplug"
        line: "hdmi_force_hotplug=1"
      - regexp: "^#?hdmi_group"
        line: "hdmi_group=1"
      - regexp: "^#?hdmi_mode"
        line: "hdmi_mode=62"
      - regexp: "^#?overscan_left"
        line: "overscan_left=-5"
      - regexp: "^#?overscan_right"
        line: "overscan_right=-5"
      - regexp: "^#?overscan_top"
        line: "overscan_top=-5"
      - regexp: "^#?overscan_bottom"
        line: "overscan_bottom=-5"

  tasks:

    # Run apt-get update and apt-get upgrade 
    - include: ../tasks/update.yml
      tags: update

    - name: Install dependancies from apt
      become: yes
      apt: name={{item}} state=installed
      with_items:
        - smbclient

    - name: Configure option values in /boot/config.txt file.
      become: yes
      lineinfile:
        dest: /boot/config.txt
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        insertafter: EOF
        state: present
      with_items: "{{ boot_config_options }}"

    # Copy roms using smbclient
    - include: ../tasks/copy-retropie-roms.yml

  handlers:

    - include: ../handlers/reboot.yml
      tags: system
